# https://travis-ci.org/pytorch/pytorch
language: python
dist: trusty
git:
  submodules: false

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true
    include:
      - env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
      - env: MYPY_TYPE_CHECK
        python: "3.6"
        install: pip install mypy mypy-extensions
        script: mypy @mypy-files.txt
      - env: CLANG_FORMAT_CHECK
        install:
          - sudo apt-get install -y clang-format-3.9 expect-dev
          - sudo ln -s /usr/bin/clang-format-3.9 /usr/bin/clang-format
          - wget https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format -O git-clang-format.py
        script:
          - unbuffer python git-clang-format.py --verbose --diff master | tee output
          - grep -E 'clang-format did not modify any files|no modified files to format' output
    allow_failures:
      - env: CLANG_FORMAT_CHECK
